### PR TITLE
When ProjectUniqueNameNew has relative path like this : "../directory…

### PR DESCRIPTION
**Pull request by voronytskyi**
…Name/FileName" -> ProjectFullNameNew will not be replaced with a new ProjectName.

### CODE REVIEW

**Comment by kuanysh-nabiyev** [comment]
Hi @voronytskyi,
Thanks for showing me bug when existing project is added to a solution.
But I cannot merge it, because you solution generate another bug if solution folder (where solution located) is same with project name.

I am busy right now, but I will fix the bug soon

**Comment by voronytskyi** [comment]
You are right, It can be a problem. I just applied fast fix for my solution needs.

Thank you very much for this extension. It`s very useful for visual studio developers!

**Comment by kuanysh-nabiyev** [comment]
Thanks, I am glad that the extension is useful

**Comment by kuanysh-nabiyev** [comment]
@voronytskyi Bug was fixed. You can install new version of extension

**Comment by voronytskyi** [comment]
Thanks!

**Comment by voronytskyi** [comment]
Tested new version - working fine for me.

**Pull request closed without merging**
